# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/data/dev/viamap/rt_mapserver_exporter/ui/mapfileexportdlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MapfileExportDlg(object):
    def setupUi(self, MapfileExportDlg):
        MapfileExportDlg.setObjectName(_fromUtf8("MapfileExportDlg"))
        MapfileExportDlg.resize(547, 579)
        MapfileExportDlg.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(MapfileExportDlg)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(MapfileExportDlg)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)
        self.tabWidget = QtGui.QTabWidget(MapfileExportDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setMargin(11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.btnChooseFile = QtGui.QToolButton(self.tab)
        self.btnChooseFile.setObjectName(_fromUtf8("btnChooseFile"))
        self.gridLayout_3.addWidget(self.btnChooseFile, 0, 2, 1, 1)
        self.txtMapFilePath = QtGui.QLineEdit(self.tab)
        self.txtMapFilePath.setText(_fromUtf8(""))
        self.txtMapFilePath.setObjectName(_fromUtf8("txtMapFilePath"))
        self.gridLayout_3.addWidget(self.txtMapFilePath, 0, 1, 1, 1)
        self.lblMapFilePath = QtGui.QLabel(self.tab)
        self.lblMapFilePath.setObjectName(_fromUtf8("lblMapFilePath"))
        self.gridLayout_3.addWidget(self.lblMapFilePath, 0, 0, 1, 1)
        self.grpMap = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpMap.sizePolicy().hasHeightForWidth())
        self.grpMap.setSizePolicy(sizePolicy)
        self.grpMap.setObjectName(_fromUtf8("grpMap"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpMap)
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblMapName = QtGui.QLabel(self.grpMap)
        self.lblMapName.setToolTip(_fromUtf8(""))
        self.lblMapName.setObjectName(_fromUtf8("lblMapName"))
        self.gridLayout_2.addWidget(self.lblMapName, 0, 0, 1, 1)
        self.lblMapImageType = QtGui.QLabel(self.grpMap)
        self.lblMapImageType.setIndent(20)
        self.lblMapImageType.setObjectName(_fromUtf8("lblMapImageType"))
        self.gridLayout_2.addWidget(self.lblMapImageType, 0, 4, 1, 1)
        self.cmbMapImageType = QtGui.QComboBox(self.grpMap)
        self.cmbMapImageType.setObjectName(_fromUtf8("cmbMapImageType"))
        self.gridLayout_2.addWidget(self.cmbMapImageType, 0, 5, 1, 1)
        self.lblMapWidth = QtGui.QLabel(self.grpMap)
        self.lblMapWidth.setObjectName(_fromUtf8("lblMapWidth"))
        self.gridLayout_2.addWidget(self.lblMapWidth, 1, 0, 1, 1)
        self.txtMapWidth = QtGui.QLineEdit(self.grpMap)
        self.txtMapWidth.setText(_fromUtf8("600"))
        self.txtMapWidth.setObjectName(_fromUtf8("txtMapWidth"))
        self.gridLayout_2.addWidget(self.txtMapWidth, 1, 1, 1, 1)
        self.lblMapHeight = QtGui.QLabel(self.grpMap)
        self.lblMapHeight.setIndent(20)
        self.lblMapHeight.setObjectName(_fromUtf8("lblMapHeight"))
        self.gridLayout_2.addWidget(self.lblMapHeight, 1, 2, 1, 1)
        self.txtMapHeight = QtGui.QLineEdit(self.grpMap)
        self.txtMapHeight.setText(_fromUtf8("600"))
        self.txtMapHeight.setObjectName(_fromUtf8("txtMapHeight"))
        self.gridLayout_2.addWidget(self.txtMapHeight, 1, 3, 1, 1)
        self.lblMapUnits = QtGui.QLabel(self.grpMap)
        self.lblMapUnits.setEnabled(False)
        self.lblMapUnits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMapUnits.setObjectName(_fromUtf8("lblMapUnits"))
        self.gridLayout_2.addWidget(self.lblMapUnits, 1, 4, 1, 1)
        self.cmbMapUnits = QtGui.QComboBox(self.grpMap)
        self.cmbMapUnits.setEnabled(False)
        self.cmbMapUnits.setObjectName(_fromUtf8("cmbMapUnits"))
        self.gridLayout_2.addWidget(self.cmbMapUnits, 1, 5, 1, 1)
        self.lblMapShapePath = QtGui.QLabel(self.grpMap)
        self.lblMapShapePath.setMinimumSize(QtCore.QSize(80, 0))
        self.lblMapShapePath.setObjectName(_fromUtf8("lblMapShapePath"))
        self.gridLayout_2.addWidget(self.lblMapShapePath, 2, 0, 1, 1)
        self.txtMapShapePath = QtGui.QLineEdit(self.grpMap)
        self.txtMapShapePath.setText(_fromUtf8(""))
        self.txtMapShapePath.setObjectName(_fromUtf8("txtMapShapePath"))
        self.gridLayout_2.addWidget(self.txtMapShapePath, 2, 1, 1, 5)
        self.txtMapName = QtGui.QLineEdit(self.grpMap)
        self.txtMapName.setToolTip(_fromUtf8(""))
        self.txtMapName.setText(_fromUtf8("QGIS-MAP"))
        self.txtMapName.setObjectName(_fromUtf8("txtMapName"))
        self.gridLayout_2.addWidget(self.txtMapName, 0, 1, 1, 3)
        self.gridLayout_3.addWidget(self.grpMap, 1, 0, 1, 3)
        self.grpWeb = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpWeb.sizePolicy().hasHeightForWidth())
        self.grpWeb.setSizePolicy(sizePolicy)
        self.grpWeb.setObjectName(_fromUtf8("grpWeb"))
        self.gridLayout_4 = QtGui.QGridLayout(self.grpWeb)
        self.gridLayout_4.setMargin(11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.txtWebImageUrl = QtGui.QLineEdit(self.grpWeb)
        self.txtWebImageUrl.setText(_fromUtf8(""))
        self.txtWebImageUrl.setObjectName(_fromUtf8("txtWebImageUrl"))
        self.gridLayout_4.addWidget(self.txtWebImageUrl, 2, 1, 1, 1)
        self.txtWebTempPath = QtGui.QLineEdit(self.grpWeb)
        self.txtWebTempPath.setToolTip(_fromUtf8(""))
        self.txtWebTempPath.setText(_fromUtf8(""))
        self.txtWebTempPath.setObjectName(_fromUtf8("txtWebTempPath"))
        self.gridLayout_4.addWidget(self.txtWebTempPath, 3, 1, 1, 1)
        self.lblWebImageUrl = QtGui.QLabel(self.grpWeb)
        self.lblWebImageUrl.setMinimumSize(QtCore.QSize(80, 0))
        self.lblWebImageUrl.setObjectName(_fromUtf8("lblWebImageUrl"))
        self.gridLayout_4.addWidget(self.lblWebImageUrl, 2, 0, 1, 1)
        self.txtWebImagePath = QtGui.QLineEdit(self.grpWeb)
        self.txtWebImagePath.setText(_fromUtf8(""))
        self.txtWebImagePath.setObjectName(_fromUtf8("txtWebImagePath"))
        self.gridLayout_4.addWidget(self.txtWebImagePath, 1, 1, 1, 1)
        self.lblMapServerUrl = QtGui.QLabel(self.grpWeb)
        self.lblMapServerUrl.setMinimumSize(QtCore.QSize(80, 0))
        self.lblMapServerUrl.setObjectName(_fromUtf8("lblMapServerUrl"))
        self.gridLayout_4.addWidget(self.lblMapServerUrl, 0, 0, 1, 1)
        self.txtWebTempPath_2 = QtGui.QLabel(self.grpWeb)
        self.txtWebTempPath_2.setMinimumSize(QtCore.QSize(80, 0))
        self.txtWebTempPath_2.setObjectName(_fromUtf8("txtWebTempPath_2"))
        self.gridLayout_4.addWidget(self.txtWebTempPath_2, 3, 0, 1, 1)
        self.lblWebImagePath = QtGui.QLabel(self.grpWeb)
        self.lblWebImagePath.setMinimumSize(QtCore.QSize(80, 0))
        self.lblWebImagePath.setObjectName(_fromUtf8("lblWebImagePath"))
        self.gridLayout_4.addWidget(self.lblWebImagePath, 1, 0, 1, 1)
        self.txtMapServerUrl = QtGui.QLineEdit(self.grpWeb)
        self.txtMapServerUrl.setText(_fromUtf8("http://localhost/cgi-bin/mapserv"))
        self.txtMapServerUrl.setObjectName(_fromUtf8("txtMapServerUrl"))
        self.gridLayout_4.addWidget(self.txtMapServerUrl, 0, 1, 1, 1)
        self.lblExternalGraphicRegexp = QtGui.QLabel(self.grpWeb)
        self.lblExternalGraphicRegexp.setMinimumSize(QtCore.QSize(80, 0))
        self.lblExternalGraphicRegexp.setToolTip(_fromUtf8(""))
        self.lblExternalGraphicRegexp.setObjectName(_fromUtf8("lblExternalGraphicRegexp"))
        self.gridLayout_4.addWidget(self.lblExternalGraphicRegexp, 4, 0, 1, 1)
        self.txtExternalGraphicRegexp = QtGui.QLineEdit(self.grpWeb)
        self.txtExternalGraphicRegexp.setToolTip(_fromUtf8(""))
        self.txtExternalGraphicRegexp.setText(_fromUtf8(""))
        self.txtExternalGraphicRegexp.setObjectName(_fromUtf8("txtExternalGraphicRegexp"))
        self.gridLayout_4.addWidget(self.txtExternalGraphicRegexp, 4, 1, 1, 1)
        self.gridLayout_3.addWidget(self.grpWeb, 2, 0, 1, 3)
        self.grpExportMethod = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpExportMethod.sizePolicy().hasHeightForWidth())
        self.grpExportMethod.setSizePolicy(sizePolicy)
        self.grpExportMethod.setMinimumSize(QtCore.QSize(0, 100))
        self.grpExportMethod.setStyleSheet(_fromUtf8(""))
        self.grpExportMethod.setFlat(False)
        self.grpExportMethod.setCheckable(False)
        self.grpExportMethod.setObjectName(_fromUtf8("grpExportMethod"))
        self.gridLayout_5 = QtGui.QGridLayout(self.grpExportMethod)
        self.gridLayout_5.setMargin(11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.checkExportSLD = QtGui.QRadioButton(self.grpExportMethod)
        self.checkExportSLD.setChecked(True)
        self.checkExportSLD.setObjectName(_fromUtf8("checkExportSLD"))
        self.buttonGroup = QtGui.QButtonGroup(MapfileExportDlg)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.checkExportSLD)
        self.gridLayout_5.addWidget(self.checkExportSLD, 0, 0, 1, 1)
        self.checkExportCustom = QtGui.QRadioButton(self.grpExportMethod)
        self.checkExportCustom.setObjectName(_fromUtf8("checkExportCustom"))
        self.buttonGroup.addButton(self.checkExportCustom)
        self.gridLayout_5.addWidget(self.checkExportCustom, 1, 0, 1, 1)
        self.lblHelpMeDecide = QtGui.QLabel(self.grpExportMethod)
        self.lblHelpMeDecide.setAutoFillBackground(False)
        self.lblHelpMeDecide.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblHelpMeDecide.setOpenExternalLinks(False)
        self.lblHelpMeDecide.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.lblHelpMeDecide.setObjectName(_fromUtf8("lblHelpMeDecide"))
        self.gridLayout_5.addWidget(self.lblHelpMeDecide, 0, 1, 1, 1)
        self.checkExportSLD.raise_()
        self.checkExportCustom.raise_()
        self.checkExportSLD.raise_()
        self.grpWeb.raise_()
        self.lblHelpMeDecide.raise_()
        self.gridLayout_3.addWidget(self.grpExportMethod, 3, 0, 1, 3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_7.setMargin(11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.checkTmplFromFile = QtGui.QRadioButton(self.tab_2)
        self.checkTmplFromFile.setChecked(True)
        self.checkTmplFromFile.setObjectName(_fromUtf8("checkTmplFromFile"))
        self.gridLayout_7.addWidget(self.checkTmplFromFile, 0, 0, 1, 3)
        self.txtTemplatePath = QtGui.QLineEdit(self.tab_2)
        self.txtTemplatePath.setText(_fromUtf8("[templatepath]"))
        self.txtTemplatePath.setObjectName(_fromUtf8("txtTemplatePath"))
        self.gridLayout_7.addWidget(self.txtTemplatePath, 0, 3, 1, 1)
        self.btnChooseTemplate = QtGui.QToolButton(self.tab_2)
        self.btnChooseTemplate.setObjectName(_fromUtf8("btnChooseTemplate"))
        self.gridLayout_7.addWidget(self.btnChooseTemplate, 0, 4, 1, 1)
        self.checkGenerateTmpl = QtGui.QRadioButton(self.tab_2)
        self.checkGenerateTmpl.setObjectName(_fromUtf8("checkGenerateTmpl"))
        self.gridLayout_7.addWidget(self.checkGenerateTmpl, 1, 0, 1, 4)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 2, 0, 1, 1)
        self.templateTable = QtGui.QTableView(self.tab_2)
        self.templateTable.setEnabled(False)
        self.templateTable.setObjectName(_fromUtf8("templateTable"))
        self.gridLayout_7.addWidget(self.templateTable, 2, 1, 1, 4)
        self.lblHeader = QtGui.QLabel(self.tab_2)
        self.lblHeader.setObjectName(_fromUtf8("lblHeader"))
        self.gridLayout_7.addWidget(self.lblHeader, 3, 0, 1, 2)
        self.txtTmplHeaderPath = QtGui.QLineEdit(self.tab_2)
        self.txtTmplHeaderPath.setText(_fromUtf8(""))
        self.txtTmplHeaderPath.setObjectName(_fromUtf8("txtTmplHeaderPath"))
        self.gridLayout_7.addWidget(self.txtTmplHeaderPath, 3, 2, 1, 2)
        self.btnChooseTmplHeader = QtGui.QToolButton(self.tab_2)
        self.btnChooseTmplHeader.setObjectName(_fromUtf8("btnChooseTmplHeader"))
        self.gridLayout_7.addWidget(self.btnChooseTmplHeader, 3, 4, 1, 1)
        self.lblFooter = QtGui.QLabel(self.tab_2)
        self.lblFooter.setObjectName(_fromUtf8("lblFooter"))
        self.gridLayout_7.addWidget(self.lblFooter, 4, 0, 1, 2)
        self.txtTmplFooterPath = QtGui.QLineEdit(self.tab_2)
        self.txtTmplFooterPath.setText(_fromUtf8(""))
        self.txtTmplFooterPath.setObjectName(_fromUtf8("txtTmplFooterPath"))
        self.gridLayout_7.addWidget(self.txtTmplFooterPath, 4, 2, 1, 2)
        self.btnChooseTmplFooter = QtGui.QToolButton(self.tab_2)
        self.btnChooseTmplFooter.setObjectName(_fromUtf8("btnChooseTmplFooter"))
        self.gridLayout_7.addWidget(self.btnChooseTmplFooter, 4, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 5, 0, 1, 5)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_8.setMargin(11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setMargin(11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lblMapFontsetPath = QtGui.QLabel(self.groupBox_3)
        self.lblMapFontsetPath.setMinimumSize(QtCore.QSize(80, 0))
        self.lblMapFontsetPath.setObjectName(_fromUtf8("lblMapFontsetPath"))
        self.gridLayout_6.addWidget(self.lblMapFontsetPath, 0, 0, 1, 1)
        self.txtMapFontsetPath = QtGui.QLineEdit(self.groupBox_3)
        self.txtMapFontsetPath.setText(_fromUtf8("[fontsetpath]"))
        self.txtMapFontsetPath.setObjectName(_fromUtf8("txtMapFontsetPath"))
        self.gridLayout_6.addWidget(self.txtMapFontsetPath, 0, 1, 1, 1)
        self.checkCreateFontFile = QtGui.QCheckBox(self.groupBox_3)
        self.checkCreateFontFile.setObjectName(_fromUtf8("checkCreateFontFile"))
        self.gridLayout_6.addWidget(self.checkCreateFontFile, 1, 0, 1, 2)
        self.gridLayout_8.addWidget(self.groupBox_3, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.lblMapFilePath.setBuddy(self.txtMapFilePath)
        self.lblMapName.setBuddy(self.txtMapName)
        self.lblMapImageType.setBuddy(self.cmbMapImageType)
        self.lblMapWidth.setBuddy(self.txtMapWidth)
        self.lblMapHeight.setBuddy(self.txtMapHeight)
        self.lblMapUnits.setBuddy(self.cmbMapUnits)
        self.lblMapShapePath.setBuddy(self.txtMapServerUrl)
        self.lblWebImageUrl.setBuddy(self.txtMapServerUrl)
        self.lblMapServerUrl.setBuddy(self.txtMapServerUrl)
        self.txtWebTempPath_2.setBuddy(self.txtMapServerUrl)
        self.lblWebImagePath.setBuddy(self.txtMapServerUrl)
        self.lblExternalGraphicRegexp.setBuddy(self.txtMapServerUrl)
        self.lblMapFontsetPath.setBuddy(self.txtMapServerUrl)

        self.retranslateUi(MapfileExportDlg)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MapfileExportDlg.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MapfileExportDlg.accept)
        QtCore.QObject.connect(self.checkGenerateTmpl, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.templateTable.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MapfileExportDlg)
        MapfileExportDlg.setTabOrder(self.txtMapFilePath, self.btnChooseFile)
        MapfileExportDlg.setTabOrder(self.btnChooseFile, self.txtMapName)
        MapfileExportDlg.setTabOrder(self.txtMapName, self.cmbMapImageType)
        MapfileExportDlg.setTabOrder(self.cmbMapImageType, self.txtMapWidth)
        MapfileExportDlg.setTabOrder(self.txtMapWidth, self.txtMapHeight)
        MapfileExportDlg.setTabOrder(self.txtMapHeight, self.cmbMapUnits)
        MapfileExportDlg.setTabOrder(self.cmbMapUnits, self.txtMapShapePath)
        MapfileExportDlg.setTabOrder(self.txtMapShapePath, self.txtMapServerUrl)
        MapfileExportDlg.setTabOrder(self.txtMapServerUrl, self.txtWebImagePath)
        MapfileExportDlg.setTabOrder(self.txtWebImagePath, self.txtWebImageUrl)
        MapfileExportDlg.setTabOrder(self.txtWebImageUrl, self.txtWebTempPath)
        MapfileExportDlg.setTabOrder(self.txtWebTempPath, self.txtExternalGraphicRegexp)
        MapfileExportDlg.setTabOrder(self.txtExternalGraphicRegexp, self.checkExportSLD)
        MapfileExportDlg.setTabOrder(self.checkExportSLD, self.checkExportCustom)
        MapfileExportDlg.setTabOrder(self.checkExportCustom, self.checkTmplFromFile)
        MapfileExportDlg.setTabOrder(self.checkTmplFromFile, self.txtTemplatePath)
        MapfileExportDlg.setTabOrder(self.txtTemplatePath, self.btnChooseTemplate)
        MapfileExportDlg.setTabOrder(self.btnChooseTemplate, self.checkGenerateTmpl)
        MapfileExportDlg.setTabOrder(self.checkGenerateTmpl, self.tabWidget)
        MapfileExportDlg.setTabOrder(self.tabWidget, self.templateTable)
        MapfileExportDlg.setTabOrder(self.templateTable, self.txtTmplHeaderPath)
        MapfileExportDlg.setTabOrder(self.txtTmplHeaderPath, self.btnChooseTmplHeader)
        MapfileExportDlg.setTabOrder(self.btnChooseTmplHeader, self.txtTmplFooterPath)
        MapfileExportDlg.setTabOrder(self.txtTmplFooterPath, self.btnChooseTmplFooter)
        MapfileExportDlg.setTabOrder(self.btnChooseTmplFooter, self.txtMapFontsetPath)
        MapfileExportDlg.setTabOrder(self.txtMapFontsetPath, self.checkCreateFontFile)

    def retranslateUi(self, MapfileExportDlg):
        MapfileExportDlg.setWindowTitle(_translate("MapfileExportDlg", "RT MapServer Exporter - Save project to MapFile", None))
        self.btnChooseFile.setText(_translate("MapfileExportDlg", "...", None))
        self.txtMapFilePath.setToolTip(_translate("MapfileExportDlg", "Name for the map file to be created from the QGIS project file", None))
        self.lblMapFilePath.setText(_translate("MapfileExportDlg", "Map file", None))
        self.grpMap.setTitle(_translate("MapfileExportDlg", "Map", None))
        self.lblMapName.setText(_translate("MapfileExportDlg", "Name", None))
        self.lblMapImageType.setText(_translate("MapfileExportDlg", "Image type", None))
        self.lblMapWidth.setText(_translate("MapfileExportDlg", "Width", None))
        self.lblMapHeight.setText(_translate("MapfileExportDlg", "Height", None))
        self.lblMapUnits.setText(_translate("MapfileExportDlg", "Units", None))
        self.lblMapShapePath.setText(_translate("MapfileExportDlg", "Shape path", None))
        self.txtMapShapePath.setToolTip(_translate("MapfileExportDlg", "Path to the folder where shapefiles are stored.", None))
        self.grpWeb.setTitle(_translate("MapfileExportDlg", "Web", None))
        self.txtWebImageUrl.setToolTip(_translate("MapfileExportDlg", "Base URL for \"Image path\".\n"
"This is the URL that will take the web browser to \"Image path\" to get the images.", None))
        self.lblWebImageUrl.setText(_translate("MapfileExportDlg", "Image URL", None))
        self.txtWebImagePath.setToolTip(_translate("MapfileExportDlg", "Path to the temporary directory for writing temporary files and images. Must be writable by the user the web server is running as. Must end with a / or depending on your platform.", None))
        self.lblMapServerUrl.setText(_translate("MapfileExportDlg", "Online resource URL", None))
        self.txtWebTempPath_2.setText(_translate("MapfileExportDlg", "Temporary path", None))
        self.lblWebImagePath.setText(_translate("MapfileExportDlg", "Image path", None))
        self.txtMapServerUrl.setToolTip(_translate("MapfileExportDlg", "The URL to the mapserver executable.\n"
"\n"
"For example: \n"
"http://my.host.com/cgi-bin/mapserv.exe", None))
        self.lblExternalGraphicRegexp.setText(_translate("MapfileExportDlg", "External graphic regexp", None))
        self.grpExportMethod.setTitle(_translate("MapfileExportDlg", "Export method for vector layer styles", None))
        self.checkExportSLD.setText(_translate("MapfileExportDlg", "SLD-based method (used by previous versions of the plugin)", None))
        self.checkExportCustom.setText(_translate("MapfileExportDlg", "New Python-based exporter", None))
        self.lblHelpMeDecide.setText(_translate("MapfileExportDlg", "<a href=\"#\">(Help me decide)</a>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MapfileExportDlg", "General", None))
        self.checkTmplFromFile.setToolTip(_translate("MapfileExportDlg", "Forces labels on, regardless of collisions. Available only for cached labels.", None))
        self.checkTmplFromFile.setText(_translate("MapfileExportDlg", "Template from file", None))
        self.txtTemplatePath.setToolTip(_translate("MapfileExportDlg", "Name for the map file to be created from the QGIS project file", None))
        self.btnChooseTemplate.setText(_translate("MapfileExportDlg", "...", None))
        self.checkGenerateTmpl.setToolTip(_translate("MapfileExportDlg", "Forces labels on, regardless of collisions. Available only for cached labels.", None))
        self.checkGenerateTmpl.setText(_translate("MapfileExportDlg", "Autogenerate template for layers", None))
        self.lblHeader.setText(_translate("MapfileExportDlg", "Header", None))
        self.txtTmplHeaderPath.setToolTip(_translate("MapfileExportDlg", "Name for the map file to be created from the QGIS project file", None))
        self.btnChooseTmplHeader.setText(_translate("MapfileExportDlg", "...", None))
        self.lblFooter.setText(_translate("MapfileExportDlg", "Footer", None))
        self.txtTmplFooterPath.setToolTip(_translate("MapfileExportDlg", "Name for the map file to be created from the QGIS project file", None))
        self.btnChooseTmplFooter.setText(_translate("MapfileExportDlg", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MapfileExportDlg", "Template", None))
        self.groupBox_3.setTitle(_translate("MapfileExportDlg", "Fontset", None))
        self.lblMapFontsetPath.setText(_translate("MapfileExportDlg", "Path", None))
        self.txtMapFontsetPath.setToolTip(_translate("MapfileExportDlg", "path", None))
        self.checkCreateFontFile.setToolTip(_translate("MapfileExportDlg", "Forces labels on, regardless of collisions. Available only for cached labels.", None))
        self.checkCreateFontFile.setText(_translate("MapfileExportDlg", "Generate used fonts file", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MapfileExportDlg", "Advanced", None))

